### ISSUE TITLE
Server-Side Rendering?

### ISSUE THREAD

**Issue by isTravis** [JedWatson/react-codemirror#21]
Any thoughts on how we could integrate this with server-side rendering? 

[React-code-mirror](https://github.com/ForbesLindesay/react-code-mirror) has a nice approach of simply generating a textarea with the content and then having codemirror hot-load over it once on the client.

**Comment by liviuignat** [comment]
Has anyone found any solution with server-side rendering?

**Comment by thealjey** [comment]
I don't care if it actually renders server side, or if it just creates a dummy `<textarea>`
but, I am pretty sure that it should not die with a `ReferenceError: navigator is not defined` error

**Comment by thealjey** [comment]
I've just created a [PR](https://github.com/JedWatson/react-codemirror/pull/31) for this.

**Comment by JedWatson** [comment]
I just merged @thealjey's PR, and published a new version. I've also updated it so the rendered textarea has the initial `value` from `props`, like @isTravis suggests from `react-code-mirror`.

Should completely resolve this issue, let me know if any of you run into more difficulties with it!

**Comment by dawsonbotsford** [comment]
We're attempting to use this component with server side rendering and still receiving the error `ReferenceError: navigator is not defined`. After searching the source code it shows that `navigator` is still included in master branch: 
https://github.com/JedWatson/react-codemirror/search?utf8=%E2%9C%93&q=navigator

Are we missing something?

**Comment by moroshko** [comment]
@JedWatson The error still appears. Could you please have a look?

**Comment by john-harding** [comment]
Don't get an error, but it doesn't load.

**Comment by riverleo** [comment]
Don't panic. use this of below.

```javascript
if (process.browser) {
  require('codemirror/mode/javascript/javascript');
}
```
